events { }

http {
    server {
        listen 9090;
        root /home/parom/IdeaProjects/COURSES/nginx-udemy-container/ubuntuNginx/;

        # use for pictures and files
        location /images {
            root /home/parom/IdeaProjects/COURSES/nginx-udemy-container/;
        }

        # use regex
        location ~ .jpg {
            return 403;
        }
    }

    server {
        listen 9095;

        location / {
            proxy_pass http://localhost:9090/;
        }

        location /img {
            proxy_pass http://localhost:9090/images/;
        }
    }

}