load_module modules/ngx_stream_module.so;

events { }

stream {
    upstream database {
           server 127.0.0.1:2222;
           server 127.0.0.1:3333;
    }

    server {
        listen 9090;                  # или listen 9090 reuseport; для производительности

        proxy_pass database;        # ← вот так правильно (без http://, без /, без ;)

        # Очень рекомендуется добавить (особенно если TCP-соединения долгие):
        #proxy_protocol on;            # если бэкенды понимают PROXY protocol
        # или
        # proxy_protocol off;         # по умолчанию

        # Полезные опции (по ситуации):
        proxy_connect_timeout  5s;
        proxy_timeout          3m;    # таймаут неактивного соединения
    }
}